import React, { useState } from 'react';
import { GovMeshRequest } from '../types';
import {
  Globe2,
  ShieldCheck,
  CheckCircle2,
  Clock,
  FileText,
  Copy,
  Check,
  RefreshCw,
  ExternalLink,
  ChevronRight,
  ArrowRight,
  AlertCircle,
  FileCode,
  Building2,
  User,
  MapPin,
  FileLock
} from 'lucide-react';

interface GovMeshRequestsPageProps {
  requests: GovMeshRequest[];
  onRefresh: () => void;
  onValidate: (id: string, remarks?: string) => Promise<void>;
  onAccept: (id: string, remarks?: string) => Promise<void>;
  onStartProcessing: (id: string, remarks?: string) => Promise<void>;
  onComplete: (id: string, remarks?: string) => Promise<void>;
  onReject: (id: string, reason?: string) => Promise<void>;
  onNavigate: (page: string) => void;
}

export const GovMeshRequestsPage: React.FC<GovMeshRequestsPageProps> = ({
  requests,
  onRefresh,
  onValidate,
  onAccept,
  onStartProcessing,
  onComplete,
  onReject,
  onNavigate
}) => {
  const [selectedReqId, setSelectedReqId] = useState<string>(requests[0]?.id || requests[0]?.applicationId || '');
  const [copiedField, setCopiedField] = useState<string | null>(null);
  const [officerRemarks, setOfficerRemarks] = useState<string>('');
  const [actionLoading, setActionLoading] = useState<boolean>(false);
  const [filterStatus, setFilterStatus] = useState<string>('ALL');

  const selectedReq = requests.find(r => r.id === selectedReqId || r.applicationId === selectedReqId) || requests[0];

  const handleCopy = (text: string, fieldName: string) => {
    navigator.clipboard.writeText(text);
    setCopiedField(fieldName);
    setTimeout(() => setCopiedField(null), 2000);
  };

  const executeAction = async (actionFn: () => Promise<void>) => {
    setActionLoading(true);
    try {
      await actionFn();
    } finally {
      setActionLoading(false);
    }
  };

  const getStatusBadge = (status: string) => {
    switch (status) {
      case 'RECEIVED':
        return <span className="px-2.5 py-1 text-xs font-semibold rounded-full bg-blue-100 text-blue-800 border border-blue-200">RECEIVED</span>;
      case 'VALIDATING':
        return <span className="px-2.5 py-1 text-xs font-semibold rounded-full bg-indigo-100 text-indigo-800 border border-indigo-200 animate-pulse">VALIDATING</span>;
      case 'ACCEPTED':
        return <span className="px-2.5 py-1 text-xs font-semibold rounded-full bg-amber-100 text-amber-800 border border-amber-200">ACCEPTED</span>;
      case 'PROCESSING':
        return <span className="px-2.5 py-1 text-xs font-semibold rounded-full bg-orange-100 text-orange-800 border border-orange-200">PROCESSING</span>;
      case 'COMPLETED':
        return <span className="px-2.5 py-1 text-xs font-semibold rounded-full bg-emerald-100 text-emerald-800 border border-emerald-200">COMPLETED</span>;
      case 'REJECTED':
        return <span className="px-2.5 py-1 text-xs font-semibold rounded-full bg-red-100 text-red-800 border border-red-200">REJECTED</span>;
      default:
        return <span className="px-2.5 py-1 text-xs font-semibold rounded-full bg-gray-100 text-gray-800">{status}</span>;
    }
  };

  const filteredRequests = requests.filter(r => {
    if (filterStatus === 'ALL') return true;
    return r.status === filterStatus;
  });

  return (
    <div className="space-y-6">
      {/* Top Header Banner */}
      <div className="bg-gradient-to-r from-slate-900 via-emerald-950 to-slate-900 rounded-xl p-6 text-white shadow-lg border border-emerald-800/40">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div className="flex items-center space-x-3">
            <div className="p-3 bg-emerald-500/20 rounded-lg border border-emerald-500/40">
              <Globe2 className="w-8 h-8 text-emerald-400" />
            </div>
            <div>
              <div className="flex items-center space-x-2">
                <h1 className="text-xl font-bold tracking-tight">GovMesh Cross-Department Requests</h1>
                <span className="px-2 py-0.5 rounded text-[11px] font-bold bg-emerald-500/30 text-emerald-300 border border-emerald-400/40">LIVE SYNC</span>
              </div>
              <p className="text-xs text-slate-300 mt-1">
                Real-time dynamic interoperability: requests generated by citizens on GovMesh Portal received directly via backend-to-backend API with SHA-256 verification.
              </p>
            </div>
          </div>
          <button
            onClick={onRefresh}
            className="flex items-center space-x-2 px-4 py-2 bg-emerald-600 hover:bg-emerald-500 rounded-lg text-xs font-bold text-white transition shadow"
          >
            <RefreshCw className="w-4 h-4" />
            <span>Refresh Feed</span>
          </button>
        </div>

        {/* Quick KPI stats */}
        <div className="grid grid-cols-2 md:grid-cols-5 gap-3 mt-6 pt-5 border-t border-slate-800/80">
          <div className="bg-slate-950/50 p-3 rounded-lg border border-slate-800">
            <div className="text-[11px] text-slate-400 font-medium">Total Ingress</div>
            <div className="text-xl font-bold text-white mt-1">{requests.length}</div>
          </div>
          <div className="bg-slate-950/50 p-3 rounded-lg border border-slate-800">
            <div className="text-[11px] text-blue-400 font-medium">Received</div>
            <div className="text-xl font-bold text-blue-400 mt-1">{requests.filter(r => r.status === 'RECEIVED').length}</div>
          </div>
          <div className="bg-slate-950/50 p-3 rounded-lg border border-slate-800">
            <div className="text-[11px] text-amber-400 font-medium">In Validation / Review</div>
            <div className="text-xl font-bold text-amber-400 mt-1">{requests.filter(r => r.status === 'VALIDATING' || r.status === 'ACCEPTED').length}</div>
          </div>
          <div className="bg-slate-950/50 p-3 rounded-lg border border-slate-800">
            <div className="text-[11px] text-orange-400 font-medium">Processing</div>
            <div className="text-xl font-bold text-orange-400 mt-1">{requests.filter(r => r.status === 'PROCESSING').length}</div>
          </div>
          <div className="bg-slate-950/50 p-3 rounded-lg border border-slate-800">
            <div className="text-[11px] text-emerald-400 font-medium">Completed</div>
            <div className="text-xl font-bold text-emerald-400 mt-1">{requests.filter(r => r.status === 'COMPLETED').length}</div>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left Column: Request List */}
        <div className="lg:col-span-5 space-y-4">
          <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden">
            <div className="p-4 border-b border-slate-100 flex items-center justify-between">
              <div className="flex items-center space-x-2">
                <FileText className="w-4 h-4 text-slate-600" />
                <h2 className="text-sm font-bold text-slate-800">Incoming GovMesh Packets</h2>
              </div>
              <select
                value={filterStatus}
                onChange={(e) => setFilterStatus(e.target.value)}
                className="text-xs border border-slate-300 rounded px-2 py-1 bg-slate-50 text-slate-700"
              >
                <option value="ALL">All Statuses ({requests.length})</option>
                <option value="RECEIVED">Received</option>
                <option value="VALIDATING">Validating</option>
                <option value="ACCEPTED">Accepted</option>
                <option value="PROCESSING">Processing</option>
                <option value="COMPLETED">Completed</option>
              </select>
            </div>

            <div className="divide-y divide-slate-100 max-h-[640px] overflow-y-auto">
              {filteredRequests.length === 0 ? (
                <div className="p-8 text-center text-slate-500 text-xs">
                  No requests matching filter "{filterStatus}".
                </div>
              ) : (
                filteredRequests.map(req => {
                  const isSelected = (selectedReq?.id === req.id || selectedReq?.applicationId === req.applicationId);
                  return (
                    <div
                      key={req.id || req.applicationId}
                      onClick={() => setSelectedReqId(req.id || req.applicationId)}
                      className={`p-4 cursor-pointer transition border-l-4 ${
                        isSelected
                          ? 'bg-amber-50/70 border-l-amber-500'
                          : 'hover:bg-slate-50 border-l-transparent'
                      }`}
                    >
                      <div className="flex items-start justify-between">
                        <div>
                          <div className="text-xs font-bold text-slate-900 font-mono flex items-center space-x-1">
                            <span>{req.applicationId}</span>
                          </div>
                          <div className="text-xs font-semibold text-slate-700 mt-1">
                            {req.citizenName} <span className="text-[11px] text-slate-500 font-normal">({req.citizenRef})</span>
                          </div>
                        </div>
                        <div>{getStatusBadge(req.status)}</div>
                      </div>

                      <div className="mt-2 flex items-center justify-between text-[11px] text-slate-500">
                        <span className="flex items-center space-x-1">
                          <MapPin className="w-3 h-3 text-slate-400" />
                          <span>{req.district}</span>
                        </span>
                        <span className="flex items-center space-x-1">
                          <ShieldCheck className="w-3 h-3 text-emerald-600" />
                          <span className="text-emerald-700 font-semibold">SHA-256 Verified</span>
                        </span>
                      </div>

                      <div className="mt-2 text-[10px] font-mono text-slate-400 flex items-center justify-between border-t border-slate-100 pt-1.5">
                        <span>Recv: {new Date(req.receivedAt).toLocaleTimeString()}</span>
                        <span className="text-amber-700 font-semibold flex items-center space-x-0.5">
                          <span>Inspect</span>
                          <ChevronRight className="w-3 h-3" />
                        </span>
                      </div>
                    </div>
                  );
                })
              )}
            </div>
          </div>
        </div>

        {/* Right Column: Selected Request Inspector & Officer Action Terminal */}
        <div className="lg:col-span-7 space-y-5">
          {selectedReq ? (
            <div className="space-y-5">
              {/* Card 1: Overview and Actions Header */}
              <div className="bg-white rounded-xl shadow-sm border border-slate-200 p-5">
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-slate-100 pb-4">
                  <div>
                    <div className="text-[11px] text-slate-500 font-semibold uppercase tracking-wider">Active Application</div>
                    <div className="text-lg font-bold font-mono text-slate-900 flex items-center space-x-2">
                      <span>{selectedReq.applicationId}</span>
                      <button
                        onClick={() => handleCopy(selectedReq.applicationId, 'appId')}
                        className="p-1 text-slate-400 hover:text-slate-600 rounded"
                        title="Copy Application ID"
                      >
                        {copiedField === 'appId' ? <Check className="w-4 h-4 text-emerald-600" /> : <Copy className="w-4 h-4" />}
                      </button>
                    </div>
                  </div>
                  <div className="flex items-center space-x-3">
                    <div className="text-right">
                      <div className="text-[10px] text-slate-400 font-medium">LIFECYCLE STATUS</div>
                      <div className="mt-0.5">{getStatusBadge(selectedReq.status)}</div>
                    </div>
                  </div>
                </div>

                {/* Acknowledgement and Correlation */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3 mt-4 bg-slate-50 p-3 rounded-lg border border-slate-200/80 text-xs">
                  <div>
                    <span className="text-slate-500 font-semibold">Rural Acknowledgement ID:</span>
                    <div className="font-mono text-slate-800 font-bold mt-0.5 flex items-center space-x-1">
                      <span>{selectedReq.acknowledgementId || `ACK-RURAL-${selectedReq.applicationId}`}</span>
                      <button
                        onClick={() => handleCopy(selectedReq.acknowledgementId || `ACK-RURAL-${selectedReq.applicationId}`, 'ackId')}
                        className="p-0.5 text-slate-400 hover:text-slate-600"
                        title="Copy ACK ID"
                      >
                        {copiedField === 'ackId' ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
                      </button>
                    </div>
                  </div>
                  <div>
                    <span className="text-slate-500 font-semibold">Correlation ID:</span>
                    <div className="font-mono text-slate-700 mt-0.5">{selectedReq.correlationId}</div>
                  </div>
                </div>

                {/* Citizen Details */}
                <div className="mt-4 grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
                  <div>
                    <span className="text-slate-500 font-semibold">Citizen Name & ID:</span>
                    <div className="font-bold text-slate-900 mt-0.5">{selectedReq.citizenName}</div>
                    <div className="text-slate-500 font-mono text-[11px]">{selectedReq.citizenRef}</div>
                  </div>
                  <div>
                    <span className="text-slate-500 font-semibold">Target Jurisdiction:</span>
                    <div className="font-bold text-slate-800 mt-0.5">{selectedReq.district}, {selectedReq.taluka || 'Khed'} (PIN: {selectedReq.pincode || '410501'})</div>
                    <div className="text-slate-500 text-[11px]">Rural Development & Panchayat Raj</div>
                  </div>
                  <div className="md:col-span-2">
                    <span className="text-slate-500 font-semibold">Requested Address Update:</span>
                    <div className="mt-1 p-2.5 bg-amber-50/50 border border-amber-200 rounded font-medium text-slate-800 text-xs">
                      {selectedReq.requestedAddress}
                    </div>
                  </div>
                </div>
              </div>

              {/* Card 2: Cryptographic Hash Verification & Honest Evidence Disclaimer */}
              <div className="bg-white rounded-xl shadow-sm border border-slate-200 p-5 space-y-4">
                <div className="flex items-center justify-between border-b border-slate-100 pb-3">
                  <div className="flex items-center space-x-2">
                    <ShieldCheck className="w-5 h-5 text-emerald-600" />
                    <h3 className="text-sm font-bold text-slate-900">Cryptographic Integrity & Evidence Verification</h3>
                  </div>
                  <span className="px-2 py-0.5 bg-emerald-100 text-emerald-800 rounded font-bold text-[10px] border border-emerald-300">
                    SHA-256 VERIFIED
                  </span>
                </div>

                <div className="space-y-3 text-xs">
                  <div>
                    <div className="flex items-center justify-between">
                      <span className="text-slate-600 font-semibold">Canonical Request Hash:</span>
                      <span className="text-[10px] font-bold text-emerald-600 flex items-center space-x-1">
                        <CheckCircle2 className="w-3 h-3" />
                        <span>MATCHED</span>
                      </span>
                    </div>
                    <div className="mt-1 p-2 bg-slate-900 text-emerald-400 font-mono text-[11px] rounded overflow-x-auto break-all">
                      {selectedReq.canonicalRequestHash}
                    </div>
                  </div>

                  <div>
                    <div className="flex items-center justify-between">
                      <span className="text-slate-600 font-semibold">Document SHA-256 Digest:</span>
                      <span className="text-[10px] font-bold text-emerald-600 flex items-center space-x-1">
                        <CheckCircle2 className="w-3 h-3" />
                        <span>MATCHED</span>
                      </span>
                    </div>
                    <div className="mt-1 p-2 bg-slate-900 text-emerald-400 font-mono text-[11px] rounded overflow-x-auto break-all">
                      {selectedReq.documentHash}
                    </div>
                  </div>

                  {/* Honest Evidence Retention Disclaimer */}
                  <div className="p-3 bg-blue-50 border border-blue-200 rounded-lg flex items-start space-x-2.5">
                    <FileLock className="w-4 h-4 text-blue-700 flex-shrink-0 mt-0.5" />
                    <div className="text-[11px] text-blue-900 leading-relaxed font-medium">
                      <strong>Evidence Retention Policy:</strong> Document binary retained in GovMesh Evidence Store. Rural Department verified document integrity using SHA-256.
                    </div>
                  </div>
                </div>
              </div>

              {/* Card 3: Authoritative Timestamp Pipeline */}
              <div className="bg-white rounded-xl shadow-sm border border-slate-200 p-5">
                <div className="flex items-center space-x-2 border-b border-slate-100 pb-3 mb-4">
                  <Clock className="w-4 h-4 text-slate-700" />
                  <h3 className="text-sm font-bold text-slate-900">Authoritative Server Timestamp Sequence (UTC)</h3>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
                  <div className="p-2.5 bg-slate-50 rounded border border-slate-200">
                    <span className="text-slate-500 font-semibold block text-[10px]">1. GovMesh Created At:</span>
                    <span className="font-mono text-slate-800 font-bold">{selectedReq.createdAt || 'N/A'}</span>
                  </div>
                  <div className="p-2.5 bg-slate-50 rounded border border-slate-200">
                    <span className="text-slate-500 font-semibold block text-[10px]">2. GovMesh Sent At:</span>
                    <span className="font-mono text-slate-800 font-bold">{selectedReq.sentAt || 'N/A'}</span>
                  </div>
                  <div className="p-2.5 bg-emerald-50 rounded border border-emerald-200">
                    <span className="text-emerald-700 font-semibold block text-[10px]">3. Rural Received At (Server Clock):</span>
                    <span className="font-mono text-emerald-900 font-bold">{selectedReq.receivedAt || 'N/A'}</span>
                  </div>
                  <div className="p-2.5 bg-slate-50 rounded border border-slate-200">
                    <span className="text-slate-500 font-semibold block text-[10px]">4. Validated At:</span>
                    <span className="font-mono text-slate-800 font-bold">{selectedReq.validatedAt || 'Pending...'}</span>
                  </div>
                  <div className="p-2.5 bg-slate-50 rounded border border-slate-200">
                    <span className="text-slate-500 font-semibold block text-[10px]">5. Accepted At:</span>
                    <span className="font-mono text-slate-800 font-bold">{selectedReq.acceptedAt || 'Pending...'}</span>
                  </div>
                  <div className="p-2.5 bg-slate-50 rounded border border-slate-200">
                    <span className="text-slate-500 font-semibold block text-[10px]">6. Processing Started At:</span>
                    <span className="font-mono text-slate-800 font-bold">{selectedReq.processingStartedAt || 'Pending...'}</span>
                  </div>
                  <div className="p-2.5 bg-slate-50 rounded border border-slate-200 sm:col-span-2">
                    <span className="text-slate-500 font-semibold block text-[10px]">7. Completed At:</span>
                    <span className="font-mono text-slate-800 font-bold">{selectedReq.completedAt || 'Pending...'}</span>
                  </div>
                </div>
              </div>

              {/* Card 4: Exact Received Request Snapshot */}
              <div className="bg-white rounded-xl shadow-sm border border-slate-200 p-5">
                <div className="flex items-center justify-between border-b border-slate-100 pb-3 mb-3">
                  <div className="flex items-center space-x-2">
                    <FileCode className="w-4 h-4 text-slate-700" />
                    <h3 className="text-sm font-bold text-slate-900">Received from GovMesh (Canonical Snapshot)</h3>
                  </div>
                  <button
                    onClick={() => handleCopy(selectedReq.rawSourceJson || JSON.stringify(selectedReq, null, 2), 'rawJson')}
                    className="flex items-center space-x-1 text-xs text-slate-600 hover:text-slate-900 font-medium"
                  >
                    {copiedField === 'rawJson' ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
                    <span>{copiedField === 'rawJson' ? 'Copied' : 'Copy JSON'}</span>
                  </button>
                </div>

                <div className="bg-slate-950 p-3 rounded-lg overflow-x-auto max-h-48 text-[11px] font-mono text-slate-300">
                  <pre>{selectedReq.rawSourceJson || JSON.stringify(selectedReq, null, 2)}</pre>
                </div>
              </div>

              {/* Card 5: Officer Review & Lifecycle Action Terminal */}
              <div className="bg-gradient-to-br from-slate-900 to-slate-950 rounded-xl p-5 text-white shadow-md border border-slate-800 space-y-4">
                <div className="flex items-center justify-between border-b border-slate-800 pb-3">
                  <div className="flex items-center space-x-2">
                    <User className="w-5 h-5 text-amber-400" />
                    <h3 className="text-sm font-bold text-white">Officer Review & Lifecycle Actions</h3>
                  </div>
                  <span className="text-xs text-slate-400 font-mono">Officer: Rajesh Patil (Pune RDO)</span>
                </div>

                <div>
                  <label className="text-xs text-slate-300 font-medium block mb-1.5">Officer Decision Notes / Remarks:</label>
                  <input
                    type="text"
                    value={officerRemarks}
                    onChange={(e) => setOfficerRemarks(e.target.value)}
                    placeholder="e.g. Gram Panchayat register updated. Cryptographic checksums verified."
                    className="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-amber-500"
                  />
                </div>

                <div className="flex flex-wrap items-center gap-2.5 pt-2">
                  <button
                    disabled={actionLoading}
                    onClick={() => executeAction(() => onValidate(selectedReq.applicationId, officerRemarks))}
                    className="px-3.5 py-2 bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 text-white rounded-lg text-xs font-bold transition shadow"
                  >
                    1. Validate Request
                  </button>

                  <button
                    disabled={actionLoading}
                    onClick={() => executeAction(() => onAccept(selectedReq.applicationId, officerRemarks))}
                    className="px-3.5 py-2 bg-amber-600 hover:bg-amber-500 disabled:opacity-50 text-white rounded-lg text-xs font-bold transition shadow"
                  >
                    2. Accept into Workflow
                  </button>

                  <button
                    disabled={actionLoading}
                    onClick={() => executeAction(() => onStartProcessing(selectedReq.applicationId, officerRemarks))}
                    className="px-3.5 py-2 bg-orange-600 hover:bg-orange-500 disabled:opacity-50 text-white rounded-lg text-xs font-bold transition shadow"
                  >
                    3. Start Processing
                  </button>

                  <button
                    disabled={actionLoading}
                    onClick={() => executeAction(() => onComplete(selectedReq.applicationId, officerRemarks))}
                    className="px-4 py-2 bg-emerald-600 hover:bg-emerald-500 disabled:opacity-50 text-white rounded-lg text-xs font-bold transition shadow flex items-center space-x-1.5"
                  >
                    <CheckCircle2 className="w-4 h-4" />
                    <span>4. Complete & Sync</span>
                  </button>

                  <button
                    disabled={actionLoading}
                    onClick={() => executeAction(() => onReject(selectedReq.applicationId, officerRemarks))}
                    className="px-3.5 py-2 bg-red-600/80 hover:bg-red-600 disabled:opacity-50 text-white rounded-lg text-xs font-bold transition shadow"
                  >
                    Reject
                  </button>
                </div>
              </div>
            </div>
          ) : (
            <div className="bg-white rounded-xl shadow-sm border border-slate-200 p-12 text-center text-slate-500">
              <Globe2 className="w-12 h-12 text-slate-300 mx-auto mb-3" />
              <p className="text-sm font-medium">Select a GovMesh request from the left panel to inspect.</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
